export const RECEIVE_STUDENT = 'RECEIVE_STUDENT';
export const SET_ROLE = 'SET_ROLE';
export const ADD_QUESTION = 'ADD_QUESTION';
export const RECEIVE_QUESTION = 'RECEIVE_QUESTION';
export const ASSIGN_QUESTION = 'ASSIGN_QUESTION';
